### ISSUE TITLE
Wrong name of output jar file with the dependencies which have classifier property

### ISSUE THREAD

**Issue by yimuniao** [mojohaus/webstart#15]
From the document, 
    https://maven.apache.org/pom.html
There is following statement.
classifier:
The classifier allows to distinguish artifacts that were built from the same POM but differ in their content. It is some optional and arbitrary string that - if present - is appended to the artifact name just after the version number. 
So, normally, when we use following dependency to get the dependency jar file, the name of the file is "wrapper-18.7.9-x64.jar" 

```
           <dependency>
        <groupId>com.mat</groupId>
        <artifactId>wrapper</artifactId>
        <version>18.7.9</version>
        <classifier>x64</classifier>
    </dependency>
```

When use "webstart-maven-plugin 1.0-beta-4", the output jar is the same as original one "wrapper-18.7.9-x64.jar". But when use "webstart-maven-plugin 1.0-beta-6", the name of output jar changes to "wrapper-x64-18.7.9.jar". It brings us many difficulties.

The behavior is difficult with other plugin and is not the same as before.

 The logic is  in FullDependencyFilenameStrategy.java, and SimpleDependencyFilenameStrategy.java,  We should move block "       if ( StringUtils.isNotEmpty( artifact.getClassifier() ) )
        {
            filename += "-" + artifact.getClassifier();
        }"  to the bottom of this method.

```
public String getDependencyFileBasename( Artifact artifact, Boolean outputJarVersion, Boolean useUniqueVersions )
{
    String filename = artifact.getArtifactId();

   if ( StringUtils.isNotEmpty( artifact.getClassifier() ) )
    {
        filename += "-" + artifact.getClassifier();
    }

    if ( outputJarVersion != null )
    {

        if ( outputJarVersion )
        {
            filename += "__V";
        }
        else
        {
            filename += "-";
        }

        if ( useUniqueVersions != null && useUniqueVersions ) 
        {
            filename += artifact.getBaseVersion();
        }
        else 
        {
            filename += artifact.getVersion();
        }
    }


    return filename;
}
```

**Comment by tchemit** [comment]
Fix in #16
