### ISSUE TITLE
`build.finalName` is ignored

### ISSUE THREAD

**Issue by imgx64** [mojohaus/webstart#27]
If I set

```
<build>
    <finalName>foo</finalName>
    ...
</build>
```

in pom.xml and run `mvn package`, the zip file is renamed to `target/foo.zip` correctly. But the jar file in `target/jnlp/...` and in the zip archive keeps the default name of `${project.artifactId}-${project.version}`.

I think it should also be renamed to `finalName`, or at least have an additional configuration option to rename it.

**Comment by khmarbaise** [comment]
You can't change the name of the artifact which is installed etc. The `finalName` is only for the `target` folder. nothing else.
