### ISSUE TITLE
Support for hardware token signing

### ISSUE THREAD

**Issue by Perneel** [mojohaus/webstart#49]
I was wondering if it is possible to sign jars with a hardware token. Since February 2017, GlobalSign only issues CodeSigning certificates with an eToken (USB). The problem with this, is that the signing configuration changes of the webstart-maven-plugin (to create a JNLP file). According to GlobalSign's website, the command for signing a jar with an eToken is as following ([full article](https://support.globalsign.com/customer/portal/articles/1702232)):

    jarsigner -keystore NONE -storetype PKCS11 -tsa http://timestamp.globalsign.com/scripts/timestamp.dll -providerClass sun.security.pkcs11.SunPKCS11 -providerArg eToken.cfg test.jar "le-d0e453de-66db-414a-8fa8-0a07cfad66b5"

Converting this to pom.xml would make it the following:

    
    <sign>
        <keystore>NONE</keystore>
        <storetype>PKCS11</storetype>
        <tsaLocation>http://timestamp.globalsign.com/scripts/timestamp.dll</tsaLocation>
        <providerClass>sun.security.pkcs11.SunPKCS11</providerClass>
        <providerArg>eToken.cfg</providerArg>
        <alias>le-d0e453de-66db-414a-8fa8-0a07cfad66b5</alias>
        <verify>true</verify>
    </sign>

- tsaLocation: I got this one from the following issue: https://github.com/mojohaus/webstart/pull/11
- providerClass: not supported?
- providerArg: not supported?

As you can see, I need to configure a providerClass and providerArg to get the signing to work, is this already supported? I don't seem to find any information on it.

**Comment by Perneel** [comment]
http://stackoverflow.com/questions/43594938/maven-jnlp-creation-with-ev-code-signing

**Comment by slawekjaranowski** [comment]
PR #58 was merged - should we close this issue? @tchemit
