### ISSUE TITLE
Filename in version.xml not correct

### ISSUE THREAD

**Issue by jurgweilenmannbradyplc** [mojohaus/webstart#6]
If you have a SNAPSHOT dependency, the filename in the war and the filename in version.xml does not match. As a result, WebStart can not download the file.

Example:
We have a dependency to jar sstl-util 1.11.0-SNAPSHOT

Filename in war/webstart: sstl-util-1.11.0-20150818.085702-5.jar

In version.xml:

``` xml
  <resource>
    <pattern>
      <name>sstl-util.jar</name>
      <version-id>1.11.0-20150818.085702-5-20150821094500</version-id>
    </pattern>
    <file>sstl-util-1.11.0-SNAPSHOT.jar</file>
  </resource>
```

Should be:

``` xml
  <resource>
    <pattern>
      <name>sstl-util.jar</name>
      <version-id>1.11.0-20150818.085702-5-20150821094500</version-id>
    </pattern>
    <file>sstl-util-1.11.0-20150818.085702-5.jar</file>
  </resource>
```

This has worked correctly in 1.0-beta-4, but does not work since 1.0-beta-5

**Comment by jerdehaas** [comment]
Running into a same issue:

At deploy phase in Jenkins suddenly the version.xml is changed to include a full version of the maven jar resource artifact while still refering to the short version. This does not happen when i build it with maven2/3 locally. Tried many version of maven all the same. 

On Jenkins:
mvn clean install -> all ok
mvn deploy -> suddenly version.xml is changed to:

`<resource>
<pattern>
<name>client-0.0.2-20150914.083802-20.jar</name>
<version-id>0.0.2-20150914.083802-20</version-id>
</pattern>
<file>client-0.0.2-SNAPSHOT.jar</file>
</resource>`

Beta5 doesnt set the version of the library artifact to client-0.0.2-20150914.083802-20.jar but     client-0.0.2-SNAPSHOT.jar, but version xml is still not good:

`<resource>
<pattern>
<name>
nl.prorail.argus-client-0.0.2-20150914.083802-20.jar
</name>
<version-id>0.0.2-20150914.083802-20</version-id>
</pattern>
<file>client-0.0.2-SNAPSHOT.jar</file>
</resource>`

As we require java8 its not possible to use beta4, vote for quick fix.

**Comment by mkotiaho** [comment]
I have this problem also.
Actual filename: `swt-win32-3.5.57.jar`
In version.xml: `swt-3.5.57-win32.jar`

This worked correctly in 1.0-beta-4, not sure about 1.0-beta-5.

**Comment by jonfreedman** [comment]
I just confirmed that 1.0-beta-7 still has this issue (& looks like that's expected based on the updates to this ticket last week).  It would be great to get a fix as currently it's not possible to launch a snapshot jnlp after it's deployed via Nexus.

**Comment by tchemit** [comment]
I will have a look this week-end or next week.

**Comment by rdp** [comment]
Yes, same failure here, worked fine with 1.0-beta-2, thanks

**Comment by tchemit** [comment]
I just create the MR for this (See #42)

**Comment by rdp** [comment]
I could really use a new version released that has this fix in it, FWIW...
